name: maisound
description: A sound app for the world to enjoy music and sound effects. Oh yeah, and it's free! And open source!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  fl_chart: any
  audioplayers: ^6.1.0
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutterflow_ui: ^0.3.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  mongo_dart: ^0.10.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/instruments/piano/
      - assets/instruments/bass/

  uses-material-design: true

